# Generated by Django 5.1.7 on 2025-05-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
