# Generated by Django 5.1.7 on 2025-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_alter_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('event-blue', 'Blue'), ('event-green', 'Green'), ('event-orange', 'Orange')], default='event-blue', max_length=20),
        ),
    ]
