# Generated by Django 5.1.7 on 2025-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_alter_event_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notecategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='notecategory',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
