# Generated by Django 5.1.7 on 2025-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_alter_notecategory_options_alter_notecategory_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notecategory',
            unique_together=set(),
        ),
    ]
